define(
{
    "toc":[
        {
            "heading":"Table of Contents",
            "topics":[
                {
                    "title":"List of Tables",
                    "href":"lot.html"
                },
                {
                    "title":"Title and Copyright Information",
                    "href":"index.html"
                },
                {
                    "title":"Preface",
                    "href":"preface.html#GUID-0441C15D-6468-4A16-8DB9-296B2DD79FDB",
                    "topics":[
                        {
                            "title":"Audience",
                            "href":"preface.html#GUID-647AE0C9-8714-4DED-9B62-022B5BCDF67B"
                        },
                        {
                            "title":"Related Documents",
                            "href":"preface.html#GUID-60782633-76D7-4191-9E95-C8126EAA9C4D"
                        },
                        {
                            "title":"Documentation Accessibility",
                            "href":"preface.html#GUID-E409CC44-9A8F-4043-82C8-6B95CD939296"
                        },
                        {
                            "title":"Conventions",
                            "href":"preface.html#GUID-1CE0E57B-2221-45D3-8022-BE8F80457A5E"
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">1 </span> Introduction to Tools and Products that Support Migration",
                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-92DDA9F9-2572-4D04-8336-0DD33AA436B6",
                    "topics":[
                        {
                            "title":"Oracle Database Features for Migration Support",
                            "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-1D725C7D-7687-41C3-BC4B-76984FF4DAA6",
                            "topics":[
                                {
                                    "title":"SQL Translation Framework",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-5AEDF137-6E67-45D9-90CD-4F6E5B439277"
                                },
                                {
                                    "title":"Support for MySQL Applications",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-DCB2253A-8ACE-4D75-B1A5-643ED25B4E8B",
                                    "topics":[
                                        {
                                            "title":"Restrictions on SQL Statement Translation",
                                            "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-85E3793F-734C-44A1-8DA7-4F9BB61B21F3"
                                        }
                                    ]
                                },
                                {
                                    "title":"Support for Identity Columns",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-14E4817B-F3BC-4D99-B471-A0ACDC303CC9",
                                    "topics":[
                                        {
                                            "title":"Creating Identity Columns",
                                            "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-26D00F52-9D80-4B18-9074-8461809BABAD"
                                        }
                                    ]
                                },
                                {
                                    "title":"Implicit Statement Results",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-11A805DF-A6E5-4F40-B945-EBC2DE1CFD54",
                                    "topics":[
                                        {
                                            "title":"JDBC Support for Implicit Results",
                                            "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-0046440F-FC96-473F-8D66-A801C9242179",
                                            "topics":[
                                                {
                                                    "title":"Processing Implicit Results in JDBC",
                                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-28B7EB6B-CBC7-4847-AA4B-C3B7DDD35E59"
                                                }
                                            ]
                                        },
                                        {
                                            "title":"OCI Support for Implicit Results",
                                            "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-66AAD7B2-B609-4CBC-94F7-161FB3294495",
                                            "topics":[
                                                {
                                                    "title":"Processing Implicit Results in OCI",
                                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-5711669E-3EEB-46FA-B318-6A60714A0FE2"
                                                }
                                            ]
                                        },
                                        {
                                            "title":"ODBC Support for Implicit Results",
                                            "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-47C75180-0211-44B5-A9A6-100557E76688",
                                            "topics":[
                                                {
                                                    "title":"Processing Implicit Results in ODBC",
                                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-23203334-1C8D-4EC4-9352-DD009431A14A"
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "title":"Enhanced SQL to PL/SQL Bind Handling",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-6FC797B4-896B-448E-BEB4-C7F32FBFC1CC",
                                    "topics":[
                                        {
                                            "title":"Invoking a Subprogram with a Nested Table Parameter",
                                            "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-7037AFC0-2DF4-4A94-BB66-385C51A71314"
                                        }
                                    ]
                                },
                                {
                                    "title":"Native SQL Support for Query Row Limits and Row Offsets",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-D64D01E2-EC0D-465B-A00D-5A554163356A",
                                    "topics":[
                                        {
                                            "title":"Limiting Bulk Selection",
                                            "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-B1AF6C80-E1F7-40EA-8AF4-4502E42D1A0C"
                                        }
                                    ]
                                },
                                {
                                    "title":"JDBC Driver Support for Application Migration",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-1B0334A2-6CE9-4BA1-986C-6658F4D1C49E"
                                },
                                {
                                    "title":"ODBC Driver Support for Application Migration",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-36E41144-6E9D-4984-9707-0548C375408D"
                                }
                            ]
                        },
                        {
                            "title":"Other Oracle Products that Enable Migration",
                            "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-6AE1B31A-0D3F-4B6B-9D87-3B2AA58E2584",
                            "topics":[
                                {
                                    "title":"OEM Tuning and Performance Packs",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-C17F6A94-51C3-4F89-B0D1-3AB72B474390"
                                },
                                {
                                    "title":"Oracle GoldenGate",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-ADF9878B-5781-4CF2-B087-D797E7E4880C"
                                },
                                {
                                    "title":"Oracle Database Gateways",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-81C68A0B-5BAF-4E63-B272-06A028C1DA4F"
                                },
                                {
                                    "title":"Oracle SQL Developer",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-0F53C456-1FCF-41E1-804D-02533E3D31B4"
                                }
                            ]
                        },
                        {
                            "title":"Migration Support for Other Database Vendors",
                            "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-E01998FB-3EF1-45A8-9B12-09DDB9D84B27",
                            "topics":[
                                {
                                    "title":"Application Support in Third-Party Databases",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-97209E36-A2FF-4A69-A26F-FC296C7FA1F6"
                                },
                                {
                                    "title":"Third-Party Database Version Support",
                                    "href":"intro-to-tools-and-products-supporting-migraiton.html#GUID-B1441C79-7E94-4819-BDFE-4D62D130EA6B"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">2 </span> SQL Translation Framework Overview",
                    "href":"SQL-translation-framework-overview.html#GUID-E496A5DA-7720-4091-8759-1F7407134FB7",
                    "topics":[
                        {
                            "title":"Architecture of SQL Translation Framework",
                            "href":"SQL-translation-framework-overview.html#GUID-BDE81AC4-66BB-4BD3-AF5C-125EE4991E00"
                        },
                        {
                            "title":"How to Use SQL Translation Framework",
                            "href":"SQL-translation-framework-overview.html#GUID-DE11EC38-6D1F-4B0A-A174-E4384DBAC3AB"
                        },
                        {
                            "title":"When to Use SQL Translation Framework",
                            "href":"SQL-translation-framework-overview.html#GUID-C7814DA0-96BA-4D15-A348-6F0960D4475F"
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">3 </span> SQL Translation Framework Configuration",
                    "href":"SQL-translation-framework-configuration.html#GUID-5E9591F6-4648-400F-B5A5-C81DE9E97421",
                    "topics":[
                        {
                            "title":"Installing and Configuring SQL Translation Framework with Oracle SQL Developer",
                            "href":"SQL-translation-framework-configuration.html#GUID-24D2E765-D761-4B52-AE61-90200497B4C2",
                            "topics":[
                                {
                                    "title":"Overview of Oracle SQL Developer Migration Support",
                                    "href":"SQL-translation-framework-configuration.html#GUID-AD96486C-9669-4A93-B3D8-BB9D089F57AD"
                                },
                                {
                                    "title":"Setting Up Oracle SQL Developer 3.2 for Windows",
                                    "href":"SQL-translation-framework-configuration.html#GUID-B9587A50-EB71-4914-A5F1-AD57455BEC48",
                                    "topics":[
                                        {
                                            "title":"Setting Up Oracle SQL Developer 3.2 Startup",
                                            "href":"SQL-translation-framework-configuration.html#GUID-0DA3E6DF-954D-481C-9FD4-D40D3D65E47D"
                                        },
                                        {
                                            "title":"Starting Oracle SQL Developer",
                                            "href":"SQL-translation-framework-configuration.html#GUID-2E1E2A2C-D6B1-4456-A4E0-2641B0D7DCA3"
                                        }
                                    ]
                                },
                                {
                                    "title":"Creating a Connection to Oracle Database",
                                    "href":"SQL-translation-framework-configuration.html#GUID-7F88A629-EBD8-4B16-8D32-EA3B6CF7AC44"
                                },
                                {
                                    "title":"Testing SQL Translation",
                                    "href":"SQL-translation-framework-configuration.html#GUID-377C0593-EE49-4CAA-908D-1127AD25B116"
                                },
                                {
                                    "title":"Creating a Translation Profile and Installing SQL Translator",
                                    "href":"SQL-translation-framework-configuration.html#GUID-51F2127B-6F2D-43F9-B135-ABFF0AF4A4BC",
                                    "topics":[
                                        {
                                            "title":"Installing SQL Translator",
                                            "href":"SQL-translation-framework-configuration.html#GUID-CE1582C4-90F9-4846-8357-1E7D429CD1A9"
                                        },
                                        {
                                            "title":"Creating a Translation Profile",
                                            "href":"SQL-translation-framework-configuration.html#GUID-0A81A9CC-ADDD-41F4-8F65-2E77EB528E35"
                                        }
                                    ]
                                },
                                {
                                    "title":"Using the SQL Translator Profile",
                                    "href":"SQL-translation-framework-configuration.html#GUID-9D14AFD9-FA8F-45CC-B3E4-CC8B52CA980B"
                                }
                            ]
                        },
                        {
                            "title":"Installing and Configuring SQL Translation Framework from Command Line",
                            "href":"SQL-translation-framework-configuration.html#GUID-3334EE42-B7BF-4BB6-A119-AAF538357CE1",
                            "topics":[
                                {
                                    "title":"Installing Oracle Sybase Translator",
                                    "href":"SQL-translation-framework-configuration.html#GUID-39583A4A-1A8F-43E5-A94D-6ACB479322C4"
                                },
                                {
                                    "title":"Setting up a SQL Translation Profile",
                                    "href":"SQL-translation-framework-configuration.html#GUID-EBB19CA3-5836-4657-8310-A93DD05EB8FC"
                                },
                                {
                                    "title":"Setting Up a Database Service to Use the SQL Translation Profile",
                                    "href":"SQL-translation-framework-configuration.html#GUID-7CF468AE-1017-4731-9670-4A751FBD668A",
                                    "topics":[
                                        {
                                            "title":"Setting Up a Database Service in Oracle Real Application Clusters",
                                            "href":"SQL-translation-framework-configuration.html#GUID-F285115D-CE1B-431E-980C-027EBE1376B3"
                                        }
                                    ]
                                },
                                {
                                    "title":"Testing Sybase SQL Translation Using the SQL Translation Profile",
                                    "href":"SQL-translation-framework-configuration.html#GUID-BFE85412-5AB7-4045-B44A-CD7B543E904A"
                                }
                            ]
                        },
                        {
                            "title":"Granting Necessary Permissions for Installing the SQL Translator",
                            "href":"SQL-translation-framework-configuration.html#GUID-E7C56B5D-546C-43B1-BF57-EF26140737B1"
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">4 </span> SQL Translation of JDBC and ODBC Applications",
                    "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-EEFC8D6D-BE9E-4B8F-A9A3-CA2639E5C0AB",
                    "topics":[
                        {
                            "title":"SQL Translation of JDBC Applications",
                            "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-63B5F2C5-BE69-4E66-88D2-55627A53D9CE",
                            "topics":[
                                {
                                    "title":"SQL Translation Profile",
                                    "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-56A0F127-4EC7-48A1-AACB-2C9F7818C779"
                                },
                                {
                                    "title":"Error Message Translation",
                                    "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-CE71D976-F3A3-4122-B476-4F4323FCE208"
                                },
                                {
                                    "title":"Converting JDBC Standard Parameter Markers",
                                    "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-04B2B3DB-FC28-4534-86AA-1F0D4A4CB773"
                                },
                                {
                                    "title":"Executing the Translated Oracle Dialect Query",
                                    "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-1099AC64-2C90-4841-A0B5-82568B0FDF41"
                                },
                                {
                                    "title":"Error Translation",
                                    "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-3FDC1365-E9BC-4E77-89F7-E299D4652C92"
                                },
                                {
                                    "title":"Using JDBC Driver for SQL Translation",
                                    "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-05725B2F-BDD7-4655-836D-110AAC8A782F"
                                }
                            ]
                        },
                        {
                            "title":"SQL Translation of ODBC Applications",
                            "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-07645E6D-106E-4770-B5A1-49BF9FB3A592",
                            "topics":[
                                {
                                    "title":"SQL Translation profile",
                                    "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-B987C492-CC41-4BEE-BE58-A3F2DF18DE41"
                                },
                                {
                                    "title":"Error Message Translation",
                                    "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-86D402F3-8896-4B2B-8483-D7640B90E687"
                                },
                                {
                                    "title":"Translating Error Messages",
                                    "href":"SQL-translation-JDBC-ODBC-applications.html#GUID-B8CA544D-6A5D-40EA-A6D3-BB977A27AD48"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">5 </span> Example: Application Migration Using SQL Translation Framework",
                    "href":"app-migration-using-SQL-translation-framework.html#GUID-9F438E3B-B674-4EE8-930F-37033DABE9E7",
                    "topics":[
                        {
                            "title":"Migrating a Sybase JDBC Application",
                            "href":"app-migration-using-SQL-translation-framework.html#GUID-A1FF1E84-8F38-4E8F-96A7-AFAEC50296D4",
                            "topics":[
                                {
                                    "title":"Application Overview",
                                    "href":"app-migration-using-SQL-translation-framework.html#GUID-D2067DDD-3E33-4A22-9C3F-33BDE6706102"
                                },
                                {
                                    "title":"Setting Up Migration",
                                    "href":"app-migration-using-SQL-translation-framework.html#GUID-1A30270D-E1A3-4838-8529-DE2E04633F34"
                                },
                                {
                                    "title":"Capturing Migration",
                                    "href":"app-migration-using-SQL-translation-framework.html#GUID-CFFD4B0C-7137-4D7E-8D2A-26EA4564ECAF"
                                },
                                {
                                    "title":"Setting Migration Preferences",
                                    "href":"app-migration-using-SQL-translation-framework.html#GUID-8EF366A4-059D-4054-B289-396F960D46B4"
                                },
                                {
                                    "title":"Converting Migration",
                                    "href":"app-migration-using-SQL-translation-framework.html#GUID-CEA91357-11B6-4256-A864-7C171AE3032B"
                                },
                                {
                                    "title":"Generating a Migration",
                                    "href":"app-migration-using-SQL-translation-framework.html#GUID-28F338D7-3512-4A60-8EF2-7FDC3C7CD9F9",
                                    "topics":[
                                        {
                                            "title":"Creating a Target Oracle User",
                                            "href":"app-migration-using-SQL-translation-framework.html#GUID-FFAE8A8F-293B-4936-A073-977652D8D94F"
                                        }
                                    ]
                                },
                                {
                                    "title":"Moving the Data",
                                    "href":"app-migration-using-SQL-translation-framework.html#GUID-DFA88B0F-9675-4E39-8717-224A8D987983"
                                }
                            ]
                        },
                        {
                            "title":"Generating Migration Reports",
                            "href":"app-migration-using-SQL-translation-framework.html#GUID-14F403E0-3CFD-4AA8-B64C-494E8BD883E8"
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">6 </span> MySQL Client Library Driver for Oracle",
                    "href":"MySQL-client-library-driver-for-oracle.html#GUID-A2E1F45E-0395-4A50-802B-F38BE70C980B",
                    "topics":[
                        {
                            "title":"Introduction to MySQL Client Library Driver for Oracle",
                            "href":"MySQL-client-library-driver-for-oracle.html#GUID-448D19E5-D804-4B6D-AA1F-C9933FFD40AE",
                            "topics":[
                                {
                                    "title":"Connecting to MySQL",
                                    "href":"MySQL-client-library-driver-for-oracle.html#GUID-F2BEC0A4-BD81-4F69-81E9-AB5ECDBEAD7A"
                                }
                            ]
                        },
                        {
                            "title":"Installation and First Use of MySQL Client Library Driver for Oracle",
                            "href":"MySQL-client-library-driver-for-oracle.html#GUID-312F2190-CFCA-485B-BC83-D1FCAEB6F08C"
                        },
                        {
                            "title":"Overview of Migration with MySQL Client Library Driver for Oracle",
                            "href":"MySQL-client-library-driver-for-oracle.html#GUID-08989CA5-A63F-4EC9-8C78-E5484EED1CD6"
                        },
                        {
                            "title":"Using MySQL Client Library Driver for Oracle",
                            "href":"MySQL-client-library-driver-for-oracle.html#GUID-873F2CA5-17A7-402B-B2C9-5A48D46C70A3",
                            "topics":[
                                {
                                    "title":"Relinking the Application with the liboramysql Driver",
                                    "href":"MySQL-client-library-driver-for-oracle.html#GUID-448B0CCF-DC4F-4D28-91D3-9105FB728E08"
                                },
                                {
                                    "title":"Connecting to Oracle Database",
                                    "href":"MySQL-client-library-driver-for-oracle.html#GUID-507B9379-5C30-4F90-B809-0EE6E7C8983F"
                                },
                                {
                                    "title":"Supported Platforms",
                                    "href":"MySQL-client-library-driver-for-oracle.html#GUID-2A6843E4-9D20-4418-924E-F8A0C93B61F5"
                                },
                                {
                                    "title":"Error Handling",
                                    "href":"MySQL-client-library-driver-for-oracle.html#GUID-0C035765-49BA-4D9D-8B4C-D69C3A9F535A"
                                },
                                {
                                    "title":"Globalization",
                                    "href":"MySQL-client-library-driver-for-oracle.html#GUID-CF36C012-2339-4057-BC0D-F0847C7AFB89"
                                },
                                {
                                    "title":"Expected Differences",
                                    "href":"MySQL-client-library-driver-for-oracle.html#GUID-61EE17AA-CC85-4FF3-92BD-84CA06580F79"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">7 </span> API Reference for Oracle MySQL Client Library Driver",
                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-7B8AD58E-3950-493F-96E8-96C597F4BE62",
                    "topics":[
                        {
                            "title":"Mapping Data Types",
                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-38AFC87F-B08C-4C4E-BF58-3762751AF8F1",
                            "topics":[
                                {
                                    "title":"Mapping Oracle Data Types to MySQL Data Types",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-FC1B20CC-C505-4237-94E9-294E89578206"
                                },
                                {
                                    "title":"Data Type Conversions for MySQL Program Variable Data Types",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-B0E39F16-326E-40DF-BBC0-F4A056526283",
                                    "topics":[
                                        {
                                            "title":"MYSQL_TYPE_BLOB",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-BEDD94C2-3D03-44B5-AD4E-040625C82C1D"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_DATE",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-F9067649-0A44-4417-A160-AFC340686B86"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_DATETIME",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-8C01E2C0-2C20-471A-A9DE-35DE0D3B262F"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_DOUBLE",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-73D53A21-859D-4329-BCC3-74D86DA9B59E"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_FLOAT",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-5B6B7820-EEE8-4185-B143-73BE082EEA56"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_LONG",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-60E517EC-7782-44C9-91A0-138899470AE4"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_LONG_BLOB",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-4ACD1EDB-CBF2-4B87-8499-D8FC6AC52F7C"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_LONGLONG",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-CCB06D31-32FD-4526-B4AD-BC8D9610FCCA"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_MEDIUM_BLOB",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-3432EE18-428A-4158-B6E0-7B90E6233E21"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_NEWDECIMAL",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-9F4644AD-003F-48B0-B59B-47BBF2E3B26C"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_SHORT",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-98CBEC9E-A31C-4B86-9646-E545DEE4BB86"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_STRING",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-A6395542-1E40-4B2C-AFB1-4084DEB8B294"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_TIME",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-2DA7F743-76BC-4FC2-9379-50CA3790E5A1"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_TIMESTAMP",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-6C12D70D-0325-45EE-9DD4-CF1A0DD75188"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_TINY",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-DA74555A-937B-4633-8629-60F9E320EA58"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_TINY_BLOB",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-93B89BFC-1690-49AB-B556-4AD011417399"
                                        },
                                        {
                                            "title":"MYSQL_TYPE_VAR_STRING",
                                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-7E7AD205-7F4C-40EF-8089-F31210F2EAE4"
                                        }
                                    ]
                                },
                                {
                                    "title":"Data Type Conversions for MySQL External Data Types (LOB Data Type Descriptors)",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-EF51ADA5-E112-4616-ABC6-B5D6835EEC5A"
                                },
                                {
                                    "title":"Data Type Conversions for Datetime and Interval Data Types",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-E34F9411-8B78-45C9-84BC-FB08710D8CE2"
                                }
                            ]
                        },
                        {
                            "title":"Error Handling",
                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-8C975985-92B2-4CCA-9C4E-0356F0ED2524"
                        },
                        {
                            "title":"Available Oracle Support for MySQL APIs",
                            "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-9C519FF6-E105-4C33-8E9E-3BAA3993101A",
                            "topics":[
                                {
                                    "title":"my_init()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-C23AEB33-4AF0-4BBF-9405-6AAABEF81258"
                                },
                                {
                                    "title":"mysql_affected_rows()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-3283262B-1EE7-40C6-B490-66FC42096040"
                                },
                                {
                                    "title":"mysql_autocommit()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-C5E4F931-372A-40E9-9F46-5DC77D502233"
                                },
                                {
                                    "title":"mysql_change_user()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-C526B2EF-3CBE-414E-B863-5499051F5584"
                                },
                                {
                                    "title":"mysql_character_set_name()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-FB926A3C-820E-4A8E-8728-576125033F81"
                                },
                                {
                                    "title":"mysql_close()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-0408A3A1-492E-408A-8BD8-DD42C1539569"
                                },
                                {
                                    "title":"mysql_commit()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-6A4E3AE5-58D7-42C2-AF79-A47A24C2F817"
                                },
                                {
                                    "title":"mysql_connect()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-D21EB15E-C4F9-467F-B574-24BBE9350078"
                                },
                                {
                                    "title":"mysql_create_db()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-00C0EFD1-6D6D-45E8-9ABD-73A9DE8628BF"
                                },
                                {
                                    "title":"mysql_data_seek()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-18EC29B5-14B5-4E01-B182-7597A4D54735"
                                },
                                {
                                    "title":"mysql_debug()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-DCC5EDD3-4658-40DB-A465-92AE444DD0A6"
                                },
                                {
                                    "title":"mysql_debug_info()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-0D185C0B-43FC-4591-BF76-C005E9FB509B"
                                },
                                {
                                    "title":"mysql_drop_db()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-69924066-D932-48B4-B7EA-13A082433BD4"
                                },
                                {
                                    "title":"mysql_dump_debug_info()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-9BA317AB-6AE1-4A77-BFE6-E1769AB26329"
                                },
                                {
                                    "title":"mysql_eof()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-45D4ECBD-63D1-4CAC-A5C6-4AD1B08DF730"
                                },
                                {
                                    "title":"mysql_errno()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-3C4DE075-3AC7-4F19-8E25-7C0EA191E4B0"
                                },
                                {
                                    "title":"mysql_error()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-6B8B05D5-EA3C-4178-9CBF-3A2CA293A00C"
                                },
                                {
                                    "title":"mysql_escape_string()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-82456078-0ECD-4900-BEAF-8C6155067B2A"
                                },
                                {
                                    "title":"mysql_fetch_field()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-FCFF46AF-C8B1-441C-BEE4-C627CA441401"
                                },
                                {
                                    "title":"mysql_fetch_field_direct()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-73958B77-1383-4FD1-B432-EBF32562B85B"
                                },
                                {
                                    "title":"mysql_fetch_fields()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-27895092-F899-40D3-8F3C-2B3F3AC83B53"
                                },
                                {
                                    "title":"mysql_fetch_lengths()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-F0C2684A-2BA6-4DB5-A856-CEC73696F8FD"
                                },
                                {
                                    "title":"mysql_fetch_row()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-7C9F0D0D-8737-4341-96E3-52AB6A123E43"
                                },
                                {
                                    "title":"mysql_field_count()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-BEE0BC3C-9D02-4ECB-ACD0-7C0ACDEC0F41"
                                },
                                {
                                    "title":"mysql_field_seek()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-9FC5FBFA-85D5-4923-939E-341FD1E18027"
                                },
                                {
                                    "title":"mysql_field_tell()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-1BBE4631-192D-4592-8209-DD71C7F8E087"
                                },
                                {
                                    "title":"mysql_free_result()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-00B9ED1B-5FDF-4291-9470-5AB6E20936A4"
                                },
                                {
                                    "title":"mysql_get_character_set_info()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-220980A6-AC76-4199-BE39-DDEF8559F893"
                                },
                                {
                                    "title":"mysql_get_client_info()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-2AFC3FF5-B2CE-4517-A84F-7E08F0BA0897"
                                },
                                {
                                    "title":"mysql_get_client_version()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-261D18E0-5C15-4797-BF00-4A3E139EBFE0"
                                },
                                {
                                    "title":"mysql_get_host_info()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-EB15CB01-69FC-479E-B41C-F11563866D78"
                                },
                                {
                                    "title":"mysql_get_proto_info()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-0871A2F5-0F07-493A-A1B6-A1C9DCE5A551"
                                },
                                {
                                    "title":"mysql_get_server_info()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-326903F3-B52D-4D71-A2F4-485CFD98535D"
                                },
                                {
                                    "title":"mysql_get_server_version()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-ACE0A050-D217-43E3-B005-CA85880768D8"
                                },
                                {
                                    "title":"mysql_get_ssl_cipher()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-DDA83F9A-BF1A-4D89-8639-BA6AD14103F3"
                                },
                                {
                                    "title":"mysql_hex_string()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-7F0B21FE-CE35-4A29-82A5-66CC6784BEA5"
                                },
                                {
                                    "title":"mysql_info()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-EEFB7044-8758-45B9-ADC2-40A50FBFAC2D"
                                },
                                {
                                    "title":"mysql_init()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-52A9C35B-3D7E-4C9C-83F2-50ED21C986C5"
                                },
                                {
                                    "title":"mysql_insert_id()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-7616D11A-F44C-44DA-8461-6CCE870BE6DA"
                                },
                                {
                                    "title":"mysql_kill()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-4C321D70-59AE-45B0-99F6-0B490197A049"
                                },
                                {
                                    "title":"mysql_library_end()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-F9A84C6E-B4BC-4BB7-9699-75BD6225EED3"
                                },
                                {
                                    "title":"mysql_library_init()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-A73F05A3-F41B-4789-A216-E233C32502CD"
                                },
                                {
                                    "title":"mysql_list_dbs()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-DDA1427B-7B21-40A0-8E55-E44B7D94980E"
                                },
                                {
                                    "title":"mysql_list_fields()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-A8B9423D-2547-4893-9E02-34526F8824ED"
                                },
                                {
                                    "title":"mysql_list_processes()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-428DBA40-0E44-4AC4-9580-08668EC72DC7"
                                },
                                {
                                    "title":"mysql_list_tables()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-0A3E522C-5793-4FEB-86E6-9B2D30CC3C24"
                                },
                                {
                                    "title":"mysql_more_results()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-1BCA2674-8010-47FE-9448-BE81D052F2F9"
                                },
                                {
                                    "title":"mysql_next_result()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-EE519A92-0F52-4F79-A20B-FE4145CA3942"
                                },
                                {
                                    "title":"mysql_num_fields()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-4C101282-D0BE-4776-B43A-5A774FAD32DC"
                                },
                                {
                                    "title":"mysql_num_rows()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-811AB953-A1EA-4568-B6E4-775957C855CF"
                                },
                                {
                                    "title":"mysql_options()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-F892653D-B70E-4B85-8BF3-33DC61D822A5"
                                },
                                {
                                    "title":"mysql_ping()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-C8F20DA8-51A6-4999-94C3-63938CE28D1C"
                                },
                                {
                                    "title":"mysql_query()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-7086E9F2-EBF8-4BE2-A184-73E82A3B36E7"
                                },
                                {
                                    "title":"mysql_read_query_result()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-E6008EDA-FDA5-4C9A-B798-CF2667571DB8"
                                },
                                {
                                    "title":"mysql_real_connect()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-E011EC9F-3658-41F2-81D0-107F21496BF0"
                                },
                                {
                                    "title":"mysql_real_escape_string()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-E48C48B5-8DA9-4B12-A5E3-2AD38E39996D"
                                },
                                {
                                    "title":"mysql_real_query()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-1363AAE5-D0FA-4222-AEB5-3BA7A284CC2E"
                                },
                                {
                                    "title":"mysql_refresh()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-F3F352F7-FA2A-48B9-9413-4BA1B67F61AB"
                                },
                                {
                                    "title":"mysql_reload()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-47899AF5-E76D-478B-A5C7-6DDA722EA9F8"
                                },
                                {
                                    "title":"mysql_rollback()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-C9EC5B10-9695-4764-99BB-7C68E494A6EE"
                                },
                                {
                                    "title":"mysql_row_seek()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-99A5B7FE-0E02-4DA2-A15D-54A4CCF9909F"
                                },
                                {
                                    "title":"mysql_row_tell()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-4AD5FD9A-0DAC-4262-81D1-9830006DED96"
                                },
                                {
                                    "title":"mysql_select_db()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-7786B7E2-3087-46E8-8187-64E34ED10FDE"
                                },
                                {
                                    "title":"mysql_send_query()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-0B208A3B-B4F3-4DE8-A357-A896FFCD6C5E"
                                },
                                {
                                    "title":"mysql_server_end()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-04BAE80F-E25C-49F9-A89A-8467A173BE15"
                                },
                                {
                                    "title":"mysql_server_init()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-A02269A4-9932-4987-90DD-4A48111BDFB3"
                                },
                                {
                                    "title":"mysql_set_character_set()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-C3D1DD41-9A4B-44E3-803C-3E9748C1700F"
                                },
                                {
                                    "title":"mysql_set_local_infile_default()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-F82469FE-D038-4439-8950-8608857573E0"
                                },
                                {
                                    "title":"mysql_set_local_infile_handler()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-9BCF1A99-779C-4B98-8E89-E7C0BD5AF759"
                                },
                                {
                                    "title":"mysql_set_server_option()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-0E7C7270-084A-4323-9A45-2F99ED8BC3AB"
                                },
                                {
                                    "title":"mysql_shutdown()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-FC81EA52-AA1A-46DC-AD0F-DD168C0C95F0"
                                },
                                {
                                    "title":"mysql_sqlstate()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-2B766E53-EAF1-4F48-9B66-850A3DC9A0C6"
                                },
                                {
                                    "title":"mysql_ssl_set()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-D365AF5E-F9A7-4EA7-A4AB-FEF54603B67A"
                                },
                                {
                                    "title":"mysql_stat()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-400FA829-C879-4EDB-B415-1D761B9044E8"
                                },
                                {
                                    "title":"mysql_stmt_affected_rows()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-442C6D36-E47F-46D2-B5E2-24E51AC5305A"
                                },
                                {
                                    "title":"mysql_stmt_attr_get()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-A158A882-1650-42D0-86A2-53DB51DAB39B"
                                },
                                {
                                    "title":"mysql_stmt_attr_set()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-82CBCD01-3058-4D27-9282-6247EF414383"
                                },
                                {
                                    "title":"mysql_stmt_bind_param()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-339D3B4F-5F72-4CC5-B051-77630E3BA98B"
                                },
                                {
                                    "title":"mysql_stmt_bind_result()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-8253D9F4-CB82-4F38-9B7F-97A6DE7B79CF"
                                },
                                {
                                    "title":"mysql_stmt_close()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-678C3C32-B0BD-412E-B1F8-D742B599A67B"
                                },
                                {
                                    "title":"mysql_stmt_data_seek()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-1837F375-F3CC-43DF-859C-424DE534D967"
                                },
                                {
                                    "title":"mysql_stmt_errno()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-56DD53FB-4A76-47A7-B8B9-14F7DC6E605F"
                                },
                                {
                                    "title":"mysql_stmt_error()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-9B5239C6-8565-4287-8788-9D44CB556FAF"
                                },
                                {
                                    "title":"mysql_stmt_execute()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-3AB10188-E7FA-46B6-A3E4-BE8595872BAC"
                                },
                                {
                                    "title":"mysql_stmt_fetch()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-A1D3CDC4-9A6A-432F-B12C-6819E411B48A"
                                },
                                {
                                    "title":"mysql_stmt_fetch_column()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-5B270380-F884-4AE6-84B9-34CFF8F9A986"
                                },
                                {
                                    "title":"mysql_stmt_field_count()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-CEE89744-3EC8-4E21-9F7F-FBEC8C0F876F"
                                },
                                {
                                    "title":"mysql_stmt_free_result()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-91F64B9D-9623-4434-9BCE-BC0736F2679C"
                                },
                                {
                                    "title":"mysql_stmt_init()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-852DA170-C1AC-4E37-A77A-9ED243B0C27E"
                                },
                                {
                                    "title":"mysql_stmt_insert_id()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-CE15F622-E42D-4011-80F7-34389DBFA30F"
                                },
                                {
                                    "title":"mysql_stmt_next_result()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-8792B313-F1D2-4DE1-94DB-9581676CA609"
                                },
                                {
                                    "title":"mysql_stmt_num_rows()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-650F5AE2-D37C-49A9-B922-1F84B1A53F89"
                                },
                                {
                                    "title":"mysql_stmt_param_count()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-E0052BAA-B9A6-4F4E-AE6B-0270F5F901D2"
                                },
                                {
                                    "title":"mysql_stmt_param_metadata()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-1A7C51C6-F01C-4781-8296-ED8115760721"
                                },
                                {
                                    "title":"mysql_stmt_prepare()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-37C8A5B4-A2CF-47F1-889D-928F7756EBCE"
                                },
                                {
                                    "title":"mysql_stmt_reset()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-7C09F46B-2F32-4890-A44E-C06CCB6B323B"
                                },
                                {
                                    "title":"mysql_stmt_result_metadata()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-2F885B55-E3B9-42AA-8838-7085F54CDD0A"
                                },
                                {
                                    "title":"mysql_stmt_row_seek()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-B35A51BF-BA47-425F-AD67-F82E3C6C7241"
                                },
                                {
                                    "title":"mysql_stmt_row_tell()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-DE55C9BC-E503-490E-9145-CA39C835AE29"
                                },
                                {
                                    "title":"mysql_stmt_send_long_data()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-519BC78E-DA22-4440-899B-6BADAB47E1A8"
                                },
                                {
                                    "title":"mysql_stmt_sqlstate()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-0C9EFE17-DB57-494D-9265-2DC009849EF9"
                                },
                                {
                                    "title":"mysql_stmt_store_result()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-DD212F54-1FBA-42B5-ACE2-ABCE711B2FB4"
                                },
                                {
                                    "title":"mysql_store_result()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-0E03BB68-E229-48D5-A237-160DD27C2D0F"
                                },
                                {
                                    "title":"mysql_thread_end()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-FB8C5378-D0BF-43C3-9587-272A7F72AEE3"
                                },
                                {
                                    "title":"mysql_thread_id()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-18DE42DB-9C74-409E-9EE3-A53909081C7B"
                                },
                                {
                                    "title":"mysql_thread_init()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-82F4EBE2-32B8-482F-BE47-5705F8EB5B08"
                                },
                                {
                                    "title":"mysql_thread_safe()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-DE3EE386-FC17-402E-B12B-3F45EE74657C"
                                },
                                {
                                    "title":"mysql_use_result()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-220CC182-641F-4527-A069-C589CC3D5335"
                                },
                                {
                                    "title":"mysql_warning_count()",
                                    "href":"API-ref-for-oracle-MySQL-client-library.html#GUID-7CA2C786-D445-4241-90E8-E00553B28CEA"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">8 </span> API Reference for SQL Translation of JDBC Applications",
                    "href":"API-ref-for-SQL-translation-of-JDBC-apps.html#GUID-7D294E1D-8FC6-4850-B3B2-3940516C09E8",
                    "topics":[
                        {
                            "title":"Translation Properties",
                            "href":"API-ref-for-SQL-translation-of-JDBC-apps.html#GUID-3C5FAC5A-D05A-4453-800F-E29E9539BDEB",
                            "topics":[
                                {
                                    "title":"sqlTranslationProfile",
                                    "href":"API-ref-for-SQL-translation-of-JDBC-apps.html#GUID-C71CF14E-FEA0-4FDB-B7C1-58F9015E2201"
                                },
                                {
                                    "title":"sqlErrorTranslationFile",
                                    "href":"API-ref-for-SQL-translation-of-JDBC-apps.html#GUID-C09F0C22-E649-4246-81D9-3E525E5F236B"
                                }
                            ]
                        },
                        {
                            "title":"OracleTranslatingConnection Interface",
                            "href":"API-ref-for-SQL-translation-of-JDBC-apps.html#GUID-27BC68F7-EB20-4D39-984A-320E2C282C64",
                            "topics":[
                                {
                                    "title":"SqlTranslationVersion",
                                    "href":"API-ref-for-SQL-translation-of-JDBC-apps.html#GUID-3D54DF84-D93F-4C47-8EA3-58B170888E68"
                                },
                                {
                                    "title":"createStatement()",
                                    "href":"API-ref-for-SQL-translation-of-JDBC-apps.html#GUID-E42312CD-FA52-4756-A166-CFFFFC3713CE"
                                },
                                {
                                    "title":"prepareCall()",
                                    "href":"API-ref-for-SQL-translation-of-JDBC-apps.html#GUID-3348FFC1-51B0-482F-B33D-D227A5769532"
                                },
                                {
                                    "title":"prepareStatement()",
                                    "href":"API-ref-for-SQL-translation-of-JDBC-apps.html#GUID-C03857B2-BEED-44A7-BD15-9CA55F9EBF4B"
                                },
                                {
                                    "title":"getSQLTranslationVersions()",
                                    "href":"API-ref-for-SQL-translation-of-JDBC-apps.html#GUID-944F5010-DFE0-496A-88B0-32732651C766"
                                }
                            ]
                        },
                        {
                            "title":"Error Translation Configuration File",
                            "href":"API-ref-for-SQL-translation-of-JDBC-apps.html#GUID-51CBE1C8-F927-46F4-83E9-2F4A24C2123D"
                        }
                    ]
                },
                {
                    "title":"Glossary",
                    "href":"glossary.html#GUID-73CFDC05-DF3B-44C2-9D8E-6D0B95265A38"
                },
                {
                    "title":"Index",
                    "href":"book-index.html"
                }
            ]
        }
    ]
});